# Generated by Django 4.1.3 on 2022-11-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_userbookrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbookrelation',
            options={'ordering': ['id'], 'verbose_name': 'Отношениe Пользователя', 'verbose_name_plural': 'Отношения Пользователей'},
        ),
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(related_name='books', through='store.UserBookRelation', to=settings.AUTH_USER_MODEL, verbose_name='Читатели'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_books', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
